server:
  port: 10181

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  retry:
    instances:
      BankingService:
        maxAttempts: 3
        waitDuration: 2s

  circuitbreaker:
    # circuit-breaker-aspect-order: 1
    instances:
      BankingService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        #percentage
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
