                  +---------+       +---------+       +---------+
                  | Payment |       | Banking |       |  Mambu  |
                  +---------+       +---------+       +---------+
                       |                 |                 |
                       |    request      |                 |
                       |--------------->|                 |
                       |                 |                 |
                       |  request        |                 |
                       |--------------->|   circuit       |
                       |                 |   breaker       |
                       |                 |<----open--------|
                       |                 |  (throw error)  |
                       |                 |                 |
                       |                 |<----error-------|
                       |                 |    (fallback)   |
                       |                 |                 |
                       |                 |    response     |
                       |                 |<----------------|
                       |    response     |                 |
                       |<----------------|                 |
                       |                 |                 |
                       |    request      |                 |
                       |--------------->|   circuit       |
                       |                 |   breaker       |
                       |                 |<---half-open----|
                       |                 | (retry request) |
                       |                 |                 |
                       |                 |    response     |
                       |                 |<----------------|
                       |    response     |                 |
                       |<----------------|                 |
                       |                 |                 |
