@startuml
participant PaymentService
participant Payment_CircuitBreaker
participant Banking_CircuitBreaker
participant BankingService
participant Mambu

alt if (Circuit breaker is open)
    PaymentService -> Banking_CircuitBreaker: request
    Banking_CircuitBreaker -> Banking_CircuitBreaker: not permitted
    Banking_CircuitBreaker -> PaymentService: throw error
else if Circuit breaker is half-open
    PaymentService -> Banking_CircuitBreaker
    BankingService -> Mambu: retry request
    Mambu --> BankingService: response
    BankingService -> PaymentService: response
else if Circuit breaker is closed
    Mambu --> BankingService: response
    BankingService -> PaymentService: response
end
@enduml